development:
  adapter: postgresql
  encoding: utf8
  database: sedus_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sedus_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: sedus_production
  pool: 5
  username: 
  password: